sudo: required
dist: trusty
language: java

matrix:
  include:
  - jdk: openjdk6
    env: BUILD=MVN

  - jdk: oraclejdk7
    env: BUILD=MVN

  - jdk: oraclejdk8
    env: BUILD=MVN

  - jdk: oraclejdk8
    env: BUILD=BAZEL

before_install:
  - case "$BUILD" in
      "BAZEL")
        echo "deb [arch=amd64] http://storage.googleapis.com/bazel-apt stable jdk1.8" | sudo tee /etc/apt/sources.list.d/bazel.list ;
        curl https://storage.googleapis.com/bazel-apt/doc/apt-key.pub.gpg | sudo apt-key add - ;
        sudo apt-get update ;;
    esac

install:
  - case "$BUILD" in
      "BAZEL")
        sudo apt-get install bazel ;;
      "MVN")
        mvn --version ;
        java -version ;
        mkdir protoc ;
        cd protoc ;
        curl -L -o protoc.zip https://github.com/google/protobuf/releases/download/v3.0.0/protoc-3.0.0-linux-x86_64.zip ;
        unzip protoc.zip ;
        sudo ln -s -T `pwd`/bin/protoc /usr/bin/protoc ;
        /usr/bin/protoc --version ;
        cd .. ;;
    esac

script:
  - case "$BUILD" in
      "BAZEL")
        bazel build --show_result=100 ... ;;
      "MVN")
        mvn clean package ;;
    esac
